/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessCode = string;
export interface AccessCodeResult {
  'isPaid' : boolean,
  'downloadToken' : [] | [DownloadToken],
  'folder' : Folder,
}
export interface CreateCheckoutInput {
  'cancelUrl' : string,
  'folderId' : FolderId,
  'successUrl' : string,
}
export interface CreateFolderInput { 'name' : string, 'priceInCents' : bigint }
export type DownloadToken = string;
export type ExternalBlob = Uint8Array;
export interface File {
  'id' : FileId,
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
  'folderId' : FolderId,
  'uploadedAt' : Timestamp,
}
export type FileId = string;
export interface Folder {
  'id' : FolderId,
  'owner' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'fileCount' : bigint,
  'accessCode' : AccessCode,
  'priceInCents' : bigint,
}
export type FolderId = string;
export interface Profile { 'name' : string, 'email' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionId = string;
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateFolderInput {
  'id' : FolderId,
  'name' : string,
  'priceInCents' : bigint,
}
export interface UpdateProfileInput { 'name' : string, 'email' : string }
export interface UploadFileInput {
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
  'folderId' : FolderId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerifyPaymentResult = { 'pending' : null } |
  { 'granted' : { 'downloadToken' : DownloadToken } } |
  { 'failed' : { 'error' : string } };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<[CreateCheckoutInput], string>,
  'createFolder' : ActorMethod<[CreateFolderInput], Folder>,
  'deleteFile' : ActorMethod<[FileId], undefined>,
  'deleteFolder' : ActorMethod<[FolderId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFolder' : ActorMethod<[FolderId], [] | [Folder]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listFiles' : ActorMethod<[FolderId], Array<File>>,
  'listFolders' : ActorMethod<[], Array<Folder>>,
  'regenerateAccessCode' : ActorMethod<[FolderId], string>,
  'saveCallerUserProfile' : ActorMethod<[UpdateProfileInput], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateFolder' : ActorMethod<[UpdateFolderInput], Folder>,
  'uploadFile' : ActorMethod<[UploadFileInput], File>,
  'validateAccessCode' : ActorMethod<[AccessCode], [] | [AccessCodeResult]>,
  'validateDownloadToken' : ActorMethod<[DownloadToken, FolderId], boolean>,
  'verifyPayment' : ActorMethod<[StripeSessionId], VerifyPaymentResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];