/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FolderId = IDL.Text;
export const CreateCheckoutInput = IDL.Record({
  'cancelUrl' : IDL.Text,
  'folderId' : FolderId,
  'successUrl' : IDL.Text,
});
export const CreateFolderInput = IDL.Record({
  'name' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const AccessCode = IDL.Text;
export const Folder = IDL.Record({
  'id' : FolderId,
  'owner' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'fileCount' : IDL.Nat,
  'accessCode' : AccessCode,
  'priceInCents' : IDL.Nat,
});
export const FileId = IDL.Text;
export const Profile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const File = IDL.Record({
  'id' : FileId,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'folderId' : FolderId,
  'uploadedAt' : Timestamp,
});
export const UpdateProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateFolderInput = IDL.Record({
  'id' : FolderId,
  'name' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const UploadFileInput = IDL.Record({
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'folderId' : FolderId,
});
export const DownloadToken = IDL.Text;
export const AccessCodeResult = IDL.Record({
  'isPaid' : IDL.Bool,
  'downloadToken' : IDL.Opt(DownloadToken),
  'folder' : Folder,
});
export const StripeSessionId = IDL.Text;
export const VerifyPaymentResult = IDL.Variant({
  'pending' : IDL.Null,
  'granted' : IDL.Record({ 'downloadToken' : DownloadToken }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func([CreateCheckoutInput], [IDL.Text], []),
  'createFolder' : IDL.Func([CreateFolderInput], [Folder], []),
  'deleteFile' : IDL.Func([FileId], [], []),
  'deleteFolder' : IDL.Func([FolderId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFolder' : IDL.Func([FolderId], [IDL.Opt(Folder)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listFiles' : IDL.Func([FolderId], [IDL.Vec(File)], ['query']),
  'listFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'regenerateAccessCode' : IDL.Func([FolderId], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFolder' : IDL.Func([UpdateFolderInput], [Folder], []),
  'uploadFile' : IDL.Func([UploadFileInput], [File], []),
  'validateAccessCode' : IDL.Func(
      [AccessCode],
      [IDL.Opt(AccessCodeResult)],
      ['query'],
    ),
  'validateDownloadToken' : IDL.Func(
      [DownloadToken, FolderId],
      [IDL.Bool],
      ['query'],
    ),
  'verifyPayment' : IDL.Func([StripeSessionId], [VerifyPaymentResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FolderId = IDL.Text;
  const CreateCheckoutInput = IDL.Record({
    'cancelUrl' : IDL.Text,
    'folderId' : FolderId,
    'successUrl' : IDL.Text,
  });
  const CreateFolderInput = IDL.Record({
    'name' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const AccessCode = IDL.Text;
  const Folder = IDL.Record({
    'id' : FolderId,
    'owner' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'fileCount' : IDL.Nat,
    'accessCode' : AccessCode,
    'priceInCents' : IDL.Nat,
  });
  const FileId = IDL.Text;
  const Profile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const File = IDL.Record({
    'id' : FileId,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'folderId' : FolderId,
    'uploadedAt' : Timestamp,
  });
  const UpdateProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateFolderInput = IDL.Record({
    'id' : FolderId,
    'name' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const UploadFileInput = IDL.Record({
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'folderId' : FolderId,
  });
  const DownloadToken = IDL.Text;
  const AccessCodeResult = IDL.Record({
    'isPaid' : IDL.Bool,
    'downloadToken' : IDL.Opt(DownloadToken),
    'folder' : Folder,
  });
  const StripeSessionId = IDL.Text;
  const VerifyPaymentResult = IDL.Variant({
    'pending' : IDL.Null,
    'granted' : IDL.Record({ 'downloadToken' : DownloadToken }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func([CreateCheckoutInput], [IDL.Text], []),
    'createFolder' : IDL.Func([CreateFolderInput], [Folder], []),
    'deleteFile' : IDL.Func([FileId], [], []),
    'deleteFolder' : IDL.Func([FolderId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFolder' : IDL.Func([FolderId], [IDL.Opt(Folder)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listFiles' : IDL.Func([FolderId], [IDL.Vec(File)], ['query']),
    'listFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'regenerateAccessCode' : IDL.Func([FolderId], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UpdateProfileInput], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFolder' : IDL.Func([UpdateFolderInput], [Folder], []),
    'uploadFile' : IDL.Func([UploadFileInput], [File], []),
    'validateAccessCode' : IDL.Func(
        [AccessCode],
        [IDL.Opt(AccessCodeResult)],
        ['query'],
      ),
    'validateDownloadToken' : IDL.Func(
        [DownloadToken, FolderId],
        [IDL.Bool],
        ['query'],
      ),
    'verifyPayment' : IDL.Func([StripeSessionId], [VerifyPaymentResult], []),
  });
};

export const init = ({ IDL }) => { return []; };